export const theme = {
  colors: {
    dark: '#1D1D21',
    pink: '#E76385',
    white: '#ffffff',
    greyLight: '#bebebe',
    grey: '#4b4c4c',
  },
  spacing: {
    small: '0.5rem',
    regular: '1rem',
    medium: '2rem',
    large: '3rem',
    xl: '4rem',
    xlHuge: '4.5rem',
    huge: '5rem',
    xHuge: '6rem',
    xxHuge: '7rem',
    xxxHuge: '8rem',
    xxxxHuge: '10rem',
    xxxxxHuge: '12rem',
    xxxxxxHuge: '20rem',
  },
  fontFamilies: {
    primary: 'Comforter Brush',
    secondary: 'Readex Pro',
  },
  fontSizes: {
    small: '0.5rem',
    regular: '1rem',
    regularmedium: '1.5rem',
    medium: '1.2rem',
    mediumLarge: '1.5rem',
    large: '2rem',
    mediumXl: '2.5rem',
    largeXl: '3rem',
    midXl: '3.5rem',
    xl: '4rem',
    huge: '5rem',
  },
  fontWeights: {
    lightest: '200',
    light: '300',
    regular: '400',
    medium: '500',
    bold: '700',
  },
  devices: {
    mini: '505px',
    tablet: '768px',
    desktop: '1024px',
    desktopL: '1280px',
    desktopXL: '1920px',
  },
};
